const journal = require('./example-5');

const journalEntries = [
  { "events": ["carrot", "exercise", "weekend"], "squirrel": false },
  { "events": ["bread", "pudding", "brushed teeth", "weekend", "touched tree"], "squirrel": false },
  { "events": ["carrot", "nachos", "brushed teeth", "cycling", "weekend"], "squirrel": false },
  { "events": ["brussel sprouts", "ice cream", "brushed teeth", "computer", "weekend"], "squirrel": false },
  { "events": ["potatoes", "candy", "brushed teeth", "exercise", "weekend", "dentist"], "squirrel": false },
  { "events": ["brussel sprouts", "pudding", "brushed teeth", "running", "weekend"], "squirrel": false },
  { "events": ["pizza", "brushed teeth", "computer", "work", "touched tree"], "squirrel": false },
  { "events": ["bread", "beer", "brushed teeth", "cycling", "work"], "squirrel": false },
  { "events": ["cauliflower", "brushed teeth", "work"], "squirrel": false },
  { "events": ["pizza", "brushed teeth", "cycling", "work"], "squirrel": false },
  { "events": ["lasagna", "nachos", "brushed teeth", "work"], "squirrel": false },
  { "events": ["brushed teeth", "weekend", "touched tree"], "squirrel": false },
  { "events": ["lettuce", "brushed teeth", "television", "weekend"], "squirrel": false },
  { "events": ["spaghetti", "brushed teeth", "work"], "squirrel": false },
  { "events": ["brushed teeth", "computer", "work"], "squirrel": false },
  { "events": ["lettuce", "nachos", "brushed teeth", "work"], "squirrel": false },
  { "events": ["carrot", "brushed teeth", "running", "work"], "squirrel": false },
  { "events": ["brushed teeth", "work"], "squirrel": false },
  { "events": ["cauliflower", "reading", "weekend"], "squirrel": false },
  { "events": ["bread", "brushed teeth", "weekend"], "squirrel": false },
  { "events": ["lasagna", "brushed teeth", "exercise", "work"], "squirrel": false },
  { "events": ["spaghetti", "brushed teeth", "reading", "work"], "squirrel": false },
  { "events": ["carrot", "ice cream", "brushed teeth", "television", "work"], "squirrel": false },
  { "events": ["spaghetti", "nachos", "work"], "squirrel": false },
  { "events": ["cauliflower", "ice cream", "brushed teeth", "cycling", "work"], "squirrel": false },
  { "events": ["spaghetti", "peanuts", "computer", "weekend"], "squirrel": true },
  { "events": ["potatoes", "ice cream", "brushed teeth", "computer", "weekend"], "squirrel": false },
  { "events": ["potatoes", "ice cream", "brushed teeth", "work"], "squirrel": false },
  { "events": ["peanuts", "brushed teeth", "running", "work"], "squirrel": false },
  { "events": ["potatoes", "exercise", "work"], "squirrel": false },
  { "events": ["pizza", "ice cream", "computer", "work"], "squirrel": false },
  { "events": ["lasagna", "ice cream", "work"], "squirrel": false },
  { "events": ["cauliflower", "candy", "reading", "weekend"], "squirrel": false },
  { "events": ["lasagna", "nachos", "brushed teeth", "running", "weekend"], "squirrel": false },
  { "events": ["potatoes", "brushed teeth", "work"], "squirrel": false },
  { "events": ["carrot", "work"], "squirrel": false },
  { "events": ["pizza", "beer", "work", "dentist"], "squirrel": false },
  { "events": ["lasagna", "pudding", "cycling", "work"], "squirrel": false },
  { "events": ["spaghetti", "brushed teeth", "reading", "work"], "squirrel": false },
  { "events": ["spaghetti", "pudding", "television", "weekend"], "squirrel": false },
  { "events": ["bread", "brushed teeth", "exercise", "weekend"], "squirrel": false },
  { "events": ["lasagna", "peanuts", "work"], "squirrel": true },
  { "events": ["pizza", "work"], "squirrel": false },
  { "events": ["potatoes", "exercise", "work"], "squirrel": false },
  { "events": ["brushed teeth", "exercise", "work"], "squirrel": false },
  { "events": ["spaghetti", "brushed teeth", "television", "work"], "squirrel": false },
  { "events": ["pizza", "cycling", "weekend"], "squirrel": false },
  { "events": ["carrot", "brushed teeth", "weekend"], "squirrel": false },
  { "events": ["carrot", "beer", "brushed teeth", "work"], "squirrel": false },
  { "events": ["pizza", "peanuts", "candy", "work"], "squirrel": true },
  { "events": ["carrot", "peanuts", "brushed teeth", "reading", "work"], "squirrel": false },
  { "events": ["potatoes", "peanuts", "brushed teeth", "work"], "squirrel": false },
  { "events": ["carrot", "nachos", "brushed teeth", "exercise", "work"], "squirrel": false },
  { "events": ["pizza", "peanuts", "brushed teeth", "television", "weekend"], "squirrel": false },
  { "events": ["lasagna", "brushed teeth", "cycling", "weekend"], "squirrel": false },
  { "events": ["cauliflower", "peanuts", "brushed teeth", "computer", "work", "touched tree"], "squirrel": false },
  { "events": ["lettuce", "brushed teeth", "television", "work"], "squirrel": false },
  { "events": ["potatoes", "brushed teeth", "computer", "work"], "squirrel": false },
  { "events": ["bread", "candy", "work"], "squirrel": false },
  { "events": ["potatoes", "nachos", "work"], "squirrel": false },
  { "events": ["carrot", "pudding", "brushed teeth", "weekend"], "squirrel": false },
  { "events": ["carrot", "brushed teeth", "exercise", "weekend", "touched tree"], "squirrel": false },
  { "events": ["brussel sprouts", "running", "work"], "squirrel": false },
  { "events": ["brushed teeth", "work"], "squirrel": false },
  { "events": ["lettuce", "brushed teeth", "running", "work"], "squirrel": false },
  { "events": ["candy", "brushed teeth", "work"], "squirrel": false },
  { "events": ["brussel sprouts", "brushed teeth", "computer", "work"], "squirrel": false },
  { "events": ["bread", "brushed teeth", "weekend"], "squirrel": false },
  { "events": ["cauliflower", "brushed teeth", "weekend"], "squirrel": false },
  { "events": ["spaghetti", "candy", "television", "work", "touched tree"], "squirrel": false },
  { "events": ["carrot", "pudding", "brushed teeth", "work"], "squirrel": false },
  { "events": ["lettuce", "brushed teeth", "work"], "squirrel": false },
  { "events": ["carrot", "ice cream", "brushed teeth", "cycling", "work"], "squirrel": false },
  { "events": ["pizza", "brushed teeth", "work"], "squirrel": false },
  { "events": ["spaghetti", "peanuts", "exercise", "weekend"], "squirrel": true },
  { "events": ["bread", "beer", "computer", "weekend", "touched tree"], "squirrel": false },
  { "events": ["brushed teeth", "running", "work"], "squirrel": false },
  { "events": ["lettuce", "peanuts", "brushed teeth", "work", "touched tree"], "squirrel": false },
  { "events": ["lasagna", "brushed teeth", "television", "work"], "squirrel": false },
  { "events": ["cauliflower", "brushed teeth", "running", "work"], "squirrel": false },
  { "events": ["carrot", "brushed teeth", "running", "work"], "squirrel": false },
  { "events": ["carrot", "reading", "weekend"], "squirrel": false },
  { "events": ["carrot", "peanuts", "reading", "weekend"], "squirrel": true },
  { "events": ["potatoes", "brushed teeth", "running", "work"], "squirrel": false },
  { "events": ["lasagna", "ice cream", "work", "touched tree"], "squirrel": false },
  { "events": ["cauliflower", "peanuts", "brushed teeth", "cycling", "work"], "squirrel": false },
  { "events": ["pizza", "brushed teeth", "running", "work"], "squirrel": false },
  { "events": ["lettuce", "brushed teeth", "work"], "squirrel": false },
  { "events": ["bread", "brushed teeth", "television", "weekend"], "squirrel": false },
  { "events": ["cauliflower", "peanuts", "brushed teeth", "weekend"], "squirrel": false }
];

const journalEvents = [
  "beer",
  "bread",
  "brushed teeth",
  "brussel sprouts",
  "candy",
  "carrot",
  "cauliflower",
  "computer",
  "cycling",
  "dentist",
  "exercise",
  "ice cream",
  "lasagna",
  "lettuce",
  "nachos",
  "peanuts",
  "pizza",
  "potatoes",
  "pudding",
  "reading",
  "running",
  "spaghetti",
  "television",
  "touched tree",
  "weekend",
  "work"
];

const journalObservations = {
  "beer": [81, 5, 4, 0],
  "bread": [77, 5, 8, 0],
  "brushed teeth": [21, 5, 64, 0],
  "brussel sprouts": [81, 5, 4, 0],
  "candy": [80, 4, 5, 1],
  "carrot": [70, 4, 15, 1],
  "cauliflower": [76, 5, 9, 0],
  "computer": [76, 4, 9, 1],
  "cycling": [76, 5, 9, 0],
  "dentist": [83, 5, 2, 0],
  "exercise": [76, 4, 9, 1],
  "ice cream": [76, 5, 9, 0],
  "lasagna": [77, 4, 8, 1],
  "lettuce": [78, 5, 7, 0],
  "nachos": [78, 5, 7, 0],
  "peanuts": [77, 0, 8, 5],
  "pizza": [76, 4, 9, 1],
  "potatoes": [75, 5, 10, 0],
  "pudding": [79, 5, 6, 0],
  "reading": [79, 4, 6, 1],
  "running": [74, 5, 11, 0],
  "spaghetti": [78, 3, 7, 2],
  "television": [76, 5, 9, 0],
  "touched tree": [76, 5, 9, 0],
  "weekend": [58, 2, 27, 3],
  "work": [27, 3, 58, 2]
};

describe('Weresquirrel', () => {
  beforeAll(() => {
    for (let entry of journalEntries) {
      journal.addEntry(entry.events, entry.squirrel);
    }
  });

  test('computeEvents works as expected', () => {
    expect(journal.computeEvents()).toStrictEqual(journalEvents);
  });

  test('computeObservations works as expected', () => {
    expect(journal.computeObservations()).toStrictEqual(journalObservations);
  });
});
